# For more information on Featureset Configuration: https://docs.beta.layer.co/docs/datacatalog/featuresets
apiVersion: 1

type: featureset

name: "application_features"
description: "Loan application features"
fabric: "f-medium"

features:
    - name: credit_income_ratio
      description: "credit amount ratio relative to the income of a client "
      source: credit_income_ratio.py
      environment: requirements.txt
    - name: annuity_income_ratio
      description: "Loan annuity percentage relative to the income of a client"
      source: annuity_income_ratio.py
      environment: requirements.txt
    - name: credit_term
      description: "The length of the payment in months"
      source: credit_term.py
      environment: requirements.txt
    - name: days_employed_ratio
      description: "Days employed relative to the age of the client"
      source: days_employed_ratio.py
      environment: requirements.txt
    - name: goods_price_loan_difference
      description: "Difference between the price of goods and the loan amount given"
      source: goods_price_diff.py
      environment: requirements.txt


materialization:
    integration_name: layer-public-datasets
